export const site = {
  name: "Sonali Paul",
  preferredName: "Sonali",
  title: "Digital Marketing Specialist",
  subtitle: "MBA · Digital Marketing & Retail Management",
  tagline:
    "Building brands with data-led campaigns, content, and growth that convert.",
  location: "Gudivada, Andhra Pradesh, India",
  email: "sonalipaul1414@gmail.com",
  phone: "+91 99852 82746",
  phoneHref: "tel:+919985282746",
  whatsapp: "https://wa.me/919985282746",
  linkedin: "https://www.linkedin.com/in/sonali-paul-3a7327284/",
  cvPath: "/CV-sonali-paul.pdf",
  photo: "/sonali-paul.jpeg",
  openFor:
    "Actively exploring Digital Marketing, Social Media, and Growth roles — full-time and internships (On-site / Hybrid / Remote).",
  recommendation: {
    quote:
      "Sonali brings creativity and discipline to digital campaigns — from content calendars to measurable campaign outcomes.",
    label: "Professional highlight",
  },
  navSubtitle: "Digital Marketing & MBA",
  heroChips: [
    { emoji: "🎯", label: "Campaigns" },
    { emoji: "📱", label: "Social Media" },
    { emoji: "🛒", label: "Shopify" },
    { emoji: "📊", label: "Analytics" },
  ],
  heroBadge: { value: "₹50k+", label: "ZEVAR Brand Revenue" },
  stats: [
    { value: "73.3%", label: "MBA Progress (LPU)" },
    { value: "₹50k+", label: "ZEVAR Brand Revenue" },
    { value: "₹18.5k+", label: "Digital Product Revenue" },
    { value: "1,000+", label: "Residents Reached (NGO)" },
    { value: "40%", label: "Waste Segregation Uplift" },
    { value: "93%", label: "Intermediate Score" },
  ],
  about: {
    paragraphs: [
      "Call me Sonali. I am an MBA candidate at Lovely Professional University, Mittal School of Business (Aug 2025 – Present), pursuing Digital Marketing and Retail Management with strong hands-on exposure to social media, content strategy, e-commerce, and campaign analytics.",
      "As Co-founder of ZEVAR, a jewellery brand born on campus, I built and scaled the brand through digital marketing and social strategies — generating ₹50,000+ in revenue, representing the brand at Swadeshi Mela, and managing a Shopify store with performance tracking via Google Analytics and Excel.",
      "My internship at RUXSTAR strengthened end-to-end digital execution: monthly content calendars, AI-assisted creative, and campaigns for customer acquisition and vendor onboarding. I also monetized digital products (ZEVAR app, HR application for Caelius Consulting) and contribute to community impact through NGO waste-management initiatives.",
    ],
    focus: [
      { title: "Digital Marketing", desc: "Campaigns, content & social growth" },
      { title: "Brand & E-commerce", desc: "ZEVAR · Shopify · customer engagement" },
      { title: "MBA @ LPU", desc: "Retail, live projects & analytics" },
    ],
  },
  marqueeSkills: [
    "DIGITAL MARKETING",
    "SOCIAL MEDIA",
    "GOOGLE ADS",
    "META ADS",
    "SEO",
    "SHOPIFY",
    "GOOGLE ANALYTICS",
    "CONTENT STRATEGY",
    "CANVA",
    "POWER BI",
    "WORDPRESS",
    "CAMPAIGN ANALYTICS",
  ],
  experience: [
    {
      id: "ruxstar",
      initials: "RX",
      role: "Digital Marketing Intern",
      company: "RUXSTAR",
      location: "Remote",
      period: "Jun 2026 – Jul 2026",
      bullets: [
        "Developed and executed digital marketing strategies to enhance brand awareness and user engagement.",
        "Planned monthly content calendars and created AI-powered marketing content for social media.",
        "Designed campaigns for customer acquisition, vendor onboarding, and platform promotion.",
        "Executed marketing campaigns to drive brand awareness, vendor onboard, and customer engagement.",
      ],
      tags: [
        "Digital Strategy",
        "Content Calendar",
        "AI Content",
        "Acquisition",
        "Vendor Onboarding",
      ],
    },
  ],
  projects: [
    {
      id: "zevar-brand",
      num: "01",
      category: "Entrepreneurship",
      filter: "Digital Marketing",
      title: "ZEVAR Jewellery Brand (Co-founder)",
      summary:
        "Built and managed a jewellery brand using digital marketing and social media strategies, with offline presence at Swadeshi Mela.",
      metrics: [
        { value: "₹50k+", label: "Brand Revenue" },
        { value: "1", label: "Swadeshi Mela Showcase" },
        { value: "100%", label: "Digital-First Branding" },
      ],
      highlights: [
        "Co-founded campus jewellery brand ZEVAR",
        "Social media & digital marketing-led growth",
        "Offline marketing & customer interaction at Swadeshi Mela",
        "End-to-end brand storytelling and promotion",
      ],
      period: "Sep 2025 – Present",
    },
    {
      id: "zevar-shopify",
      num: "02",
      category: "E-commerce",
      filter: "E-commerce",
      title: "Shopify Store Management — ZEVAR",
      summary:
        "Managed and optimized a Shopify-based e-commerce store to improve customer engagement and online sales.",
      metrics: [
        { value: "Shopify", label: "Store Platform" },
        { value: "GA", label: "Performance Tracking" },
        { value: "Excel", label: "Reporting" },
      ],
      highlights: [
        "Store optimization for engagement & sales",
        "Google Analytics for website performance",
        "Excel reporting for campaign insights",
        "Customer journey improvements",
      ],
      period: "May 2026",
    },
    {
      id: "zevar-app",
      num: "03",
      category: "Digital Product",
      filter: "Innovation",
      title: "Digital Product Creator — ZEVAR App",
      summary:
        "Monetized a mobile application focused on customer experience and usability.",
      metrics: [
        { value: "₹10k", label: "App Revenue" },
        { value: "1", label: "Mobile Product" },
        { value: "100%", label: "UX Focus" },
      ],
      highlights: [
        "Product promotion & user engagement",
        "Digital branding for the ZEVAR ecosystem",
        "Customer-centric app experience",
        "Revenue from digital product launch",
      ],
      period: "Jan 2026",
    },
    {
      id: "hr-app",
      num: "04",
      category: "HR Tech",
      filter: "Innovation",
      title: "HR Application Development",
      summary:
        "Created a basic HR application and sold it to Caelius Consulting Groups, Hyderabad.",
      metrics: [
        { value: "₹8,500", label: "Sale Revenue" },
        { value: "1", label: "Client Delivery" },
        { value: "100%", label: "Workflow Simplified" },
      ],
      highlights: [
        "Built HR workflow application",
        "Sold to Caelius Consulting Groups",
        "Improved client operational workflow",
        "End-to-end product handoff",
      ],
      period: "Nov 2025",
    },
    {
      id: "brand-sell",
      num: "05",
      category: "Marketing Project",
      filter: "Digital Marketing",
      title: "Brand Sell — Marketing Project",
      summary:
        "Market research and competitor analysis to identify customer trends and business opportunities.",
      metrics: [
        { value: "MR", label: "Market Research" },
        { value: "Brand", label: "Positioning" },
        { value: "Target", label: "Customer Focus" },
      ],
      highlights: [
        "Competitor & market analysis",
        "Branding & positioning strategies",
        "Customer trend identification",
        "Actionable targeting recommendations",
      ],
      period: "Sep 2025",
    },
    {
      id: "ngo",
      num: "06",
      category: "Social Impact",
      filter: "Social Impact",
      title: "NGO Waste Management Initiative",
      summary:
        "Partnered with NGOs on waste management and awareness campaigns in local communities.",
      metrics: [
        { value: "1,000+", label: "Residents Reached" },
        { value: "40%", label: "Participation Uplift" },
        { value: "3 mo", label: "Impact Window" },
      ],
      highlights: [
        "Waste management initiatives with NGOs",
        "Household segregation participation +40%",
        "Awareness campaigns & educational materials",
        "Community engagement & outreach",
      ],
      period: "Sep – Nov 2024",
    },
  ],
  education: [
    {
      level: "Master's Degree",
      school: "Lovely Professional University",
      degree: "MBA — Digital Marketing and Retail Management",
      detail: "Percentage: 73.3%",
      period: "Aug 2025 – Present",
      location: "Phagwara, Punjab",
    },
    {
      level: "Bachelor's Degree",
      school: "Krishna University",
      degree: "Bachelor of Science — Chemistry",
      detail: "Percentage: 70%",
      period: "Oct 2021 – Mar 2024",
      location: "Gudivada, Andhra Pradesh",
    },
    {
      level: "Schooling",
      school: "Sri Chaitanya Junior College",
      degree: "Intermediate (10+2)",
      detail: "Percentage: 93%",
      period: "Oct 2019 – May 2021",
      location: "Gudivada, Andhra Pradesh",
    },
  ],
  certifications: [
    {
      tag: "AI",
      date: "Jun 2026",
      title: "Generative AI Tools Certificate",
      issuer: "Be10X",
    },
    {
      tag: "National",
      date: "Nov 2025",
      title: "My Bharat Certification",
      issuer: "Saurabh Bajaj",
    },
    {
      tag: "Finance",
      date: "Oct 2025",
      title: "NISM Research Analyst Series XV",
      issuer: "NISM",
    },
    {
      tag: "Marketing",
      date: "Oct 2025",
      title: "Practical Marketer Certification",
      issuer: "Marketing Program",
    },
    {
      tag: "Data",
      date: "Sep 2023",
      title: "SQL and Relational Databases 101",
      issuer: "IBM Cognitive Class",
    },
    {
      tag: "Data",
      date: "Sep 2023",
      title: "Python 101 for Data Science",
      issuer: "IBM Cognitive Class",
    },
  ],
  accolades: [
    {
      title: "ZEVAR — Campus Brand & Swadeshi Mela",
      date: "Sep 2025",
      org: "ZEVAR Jewellery",
      desc: "Co-founded ZEVAR and represented the brand at Swadeshi Mela with ₹50,000+ revenue through digital and offline marketing.",
    },
    {
      title: "Digital Product Revenue — ZEVAR App",
      date: "Jan 2026",
      org: "ZEVAR",
      desc: "Monetized the ZEVAR mobile app with ₹10,000 in revenue through promotion and user engagement.",
    },
    {
      title: "HR App Sale — Caelius Consulting",
      date: "Nov 2025",
      org: "Caelius Consulting Groups, Hyderabad",
      desc: "Built and sold an HR application for ₹8,500, streamlining client workflow.",
    },
    {
      title: "Fluent Voices — Round Table (LPU)",
      date: "Feb 2026",
      org: "Fluent Voices Club · LPU",
      desc: "Participated in The Round Table group discussion event.",
    },
  ],
  skillGroups: [
    {
      id: "all",
      label: "All Skills",
      skills: [] as string[],
    },
    {
      id: "marketing",
      label: "Digital Marketing",
      skills: [
        "Campaign Strategy",
        "Social Media Marketing",
        "Content Calendars",
        "SEO",
        "Google Ads",
        "Meta Ads",
        "Brand Positioning",
        "Customer Acquisition",
      ],
    },
    {
      id: "ecommerce",
      label: "E-commerce & Analytics",
      skills: [
        "Shopify Store Management",
        "Google Analytics",
        "Google Search Console",
        "Campaign Analytics",
        "Excel Reporting",
        "Power BI",
        "CRM",
      ],
    },
    {
      id: "tools",
      label: "Tools & Creative",
      skills: [
        "Canva",
        "WordPress",
        "LinkedIn",
        "InVideo AI",
        "MS PowerPoint",
        "IBM SPSS",
      ],
    },
    {
      id: "power",
      label: "Power Skills",
      skills: [
        "Adaptability",
        "Leadership",
        "People Management",
        "Communication",
        "Analytical Thinking",
        "Problem-Solving",
        "Team Collaboration",
      ],
    },
  ],
  toolCategories: [
    {
      title: "Marketing & Growth",
      count: 4,
      tools: [
        {
          initial: "G",
          name: "Google Ads",
          role: "Paid Media",
          desc: "Search and display campaigns for acquisition and brand reach.",
        },
        {
          initial: "M",
          name: "Meta Ads",
          role: "Social Ads",
          desc: "Audience targeting, creative testing, and engagement campaigns.",
        },
        {
          initial: "L",
          name: "LinkedIn",
          role: "Professional Brand",
          desc: "Networking, employer branding, and B2B outreach.",
        },
        {
          initial: "S",
          name: "SEO",
          role: "Organic Growth",
          desc: "On-page optimization and search visibility.",
        },
      ],
    },
    {
      title: "Analytics & Data",
      count: 4,
      tools: [
        {
          initial: "GA",
          name: "Google Analytics",
          role: "Web Analytics",
          desc: "Traffic, behavior, and conversion tracking.",
        },
        {
          initial: "X",
          name: "MS Excel",
          role: "Reporting",
          desc: "Campaign dashboards and performance summaries.",
        },
        {
          initial: "P",
          name: "Power BI",
          role: "Dashboards",
          desc: "Visual insights for marketing and operations data.",
        },
        {
          initial: "I",
          name: "IBM SPSS",
          role: "Analysis",
          desc: "Statistical analysis for research and projects.",
        },
      ],
    },
    {
      title: "Content & Commerce",
      count: 4,
      tools: [
        {
          initial: "C",
          name: "Canva",
          role: "Design",
          desc: "Social creatives, posters, and brand assets.",
        },
        {
          initial: "Sh",
          name: "Shopify",
          role: "E-commerce",
          desc: "Store management for ZEVAR and online sales.",
        },
        {
          initial: "W",
          name: "WordPress",
          role: "Web",
          desc: "Content sites and landing experiences.",
        },
        {
          initial: "AI",
          name: "InVideo AI",
          role: "Video",
          desc: "AI-assisted video content for campaigns.",
        },
      ],
    },
  ],
  extracurricular: [
    "Participated in The Round Table — Fluent Voices Club, LPU (Feb 2026)",
    "Competitive Dancer — discipline and stage confidence (Aug 2024)",
    "Visual Artist — creativity and design thinking (Nov 2023)",
  ],
  nav: [
    { href: "#about", label: "About" },
    { href: "#experience", label: "Experience" },
    { href: "#skills", label: "Skills & Tools" },
    { href: "#projects", label: "Projects" },
    { href: "#education", label: "Education" },
    { href: "#contact", label: "Contact" },
  ],
  projectFilters: [
    "All Projects",
    "Digital Marketing",
    "E-commerce",
    "Innovation",
    "Social Impact",
  ],
  contactInterests: [
    "Full-Time Digital Marketing Role",
    "Social Media & Content Role",
    "Internship / Trainee",
    "E-commerce & Brand Project",
    "Other Collaboration",
  ],
};

site.skillGroups[0].skills = site.skillGroups
  .slice(1)
  .flatMap((g) => g.skills);
